name: Build iOS
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 🔗 GDExtension Build
        uses: godotengine/godot-cpp-template/.github/actions/build@main
        with:
          platform: ios
          arch: ${{ matrix.arch }}
          build-target-type: template_release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-riscv-ios-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/bin/**/libgodot_riscv.ios.template_release${{ matrix.ios_precision_extension }}.arm64.framework/**
          if-no-files-found: error
