name: Build Android
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
          - arch: arm32
          - arch: x86_64
          - arch: x86_32
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 🔗 GDExtension Build
        uses: godotengine/godot-cpp-template/.github/actions/build@main
        with:
          platform: android
          arch: ${{ matrix.arch }}
          build-target-type: template_release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-riscv-android-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/bin/**/*.so
          if-no-files-found: error
