name: Godot Builds
on:
  workflow_call:

jobs:
  godot:
    runs-on: "ubuntu-latest"
    name: Copy addon files

    steps:
      - uses: actions/checkout@v4
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-riscv-gdextension
          path: |
            bin
            !bin${{ matrix.dimensions }}/export_presets.cfg
            !bin${{ matrix.dimensions }}/project.godot
            !bin${{ matrix.dimensions }}/test.gd
            !bin${{ matrix.dimensions }}/test.tscn
          if-no-files-found: error
